### ISSUE TITLE
channel founders get forgotten sometimes (perhaps, when server is restarted)

### ISSUE THREAD

**Issue by silentwings** [spring/uberserver#234] opened 2017-10-06 17:34 UTC
e.g. KING channel

**Comment by abma** [comment] 2017-10-06 19:43
this happens every time when the lobby server is restarted: channel founder / op / ... isn't stored in db.

basicly code for channel settings save / load doesn't exist.

**Comment by abma** [comment] 2017-10-06 19:44
duplicate of #123

**Closed by abma** 2017-10-06 19:44 UTC
