### ISSUE TITLE
Doesn't work at all anymore in ubuntu LTS.

### ISSUE THREAD

**Issue by joeyhub** [spring/uberserver#257] opened 2018-04-05 17:32 UTC
Could you fix the instructions for LTS? Nothing works anymore. Half of the dependencies don't exist on ubuntu LTS.

**Comment by joeyhub** [comment] 2018-04-05 17:42
Issues:

1. Out of date wiki.
2. The dependencies to install aren't correct.
3. Impossible to get dependencies with issues like Error: conflicting types for ‘BIO_callback_ctrl’
4. Many people don't even need mysql, openssl, etc. There should be a set up for LAN and WAN.

**Comment by joeyhub** [comment] 2018-04-05 17:48
You also have dependencies on socketserver which doesn't exist anymore and you have specific versions in the requirements many of which appear to be broken.

**Comment by joeyhub** [comment] 2018-04-05 17:52
AttributeError: module 'lib' has no attribute 'ASN1_GENERALIZEDTIME_set_string'

**Comment by joeyhub** [comment] 2018-04-05 18:12
Half the problem is your use of python which is an absolute dependency nightmare. If you take some of the versions from requirements and just let it install the latest it works a bit better.

You still have problems though like I can't connect, I get invalid password.

It used to take 1 minute to setup LAN play and now it takes hours.

**Comment by joeyhub** [comment] 2018-04-05 18:14
Now it's in an infinite loop of asking to accept the server key.

**Comment by joeyhub** [comment] 2018-04-05 18:15
It also crashes springlobby.

**Comment by abma** [comment] 2018-04-05 22:34
sorry, the wiki page was a (outdated) duplicate of the [Readme](https://github.com/spring/uberserver/blob/master/README.md#installation)

**Closed by abma** 2018-04-05 22:34 UTC
